${self:service}-users-${sls:stage} 已经自动区分环境了：

# dev 环境
aws-serverless-infrastructure-users-dev

# prod 环境
aws-serverless-infrastructure-users-prod

# staging 环境
aws-serverless-infrastructure-users-staging


.env 文件按环境区分

# Serverless Framework 4 自动加载对应环境的 .env
.env          # 所有环境共用的默认值
.env.dev      # sls deploy --stage dev 时加载
.env.prod     # sls deploy --stage prod 时加载


// serverless.ts — 不需要额外配置，Framework 4 自动处理
const serverlessConfiguration: AWS = {
  useDotenv: true,  // ← 这一行开启就够了
}


IS_OFFLINE 问题

// ❌ 不应该 hardcode 在 serverless.ts 里
IS_OFFLINE: false,

// ✅ 只在本地 .env 里设置，部署时不存在这个变量就是 false


# .env.dev (本地开发，不提交 git)
DYNAMODB_ENDPOINT=http://localhost:8001
IS_OFFLINE=true

# .env.prod (生产，不提交 git)
# 不设置 IS_OFFLINE，默认 undefined = falsy


// serverless.ts — 只保留动态生成的值
provider: {
  environment: {
    USERS_TABLE: '${self:service}-users-${sls:stage}',
    // 删除 IS_OFFLINE，让 .env 控制
  },
},


// dynamoClient.ts — IS_OFFLINE 从 .env 读取
const client = new DynamoDBClient({
  ...(process.env.DYNAMODB_ENDPOINT && {
    endpoint: process.env.DYNAMODB_ENDPOINT,
    region: 'us-east-1',
    credentials: {
      accessKeyId: 'local',
      secretAccessKey: 'local',
    },
  }),
});


.gitignore

.env
.env.dev
.env.prod
.env.local

# 只提交模板
# .env.example ✅


.env.example（提交 git）

# Local development only
DYNAMODB_ENDPOINT=http://localhost:8001
IS_OFFLINE=true

# Auto-generated by serverless.ts, no need to set manually
# USERS_TABLE=aws-serverless-infrastructure-users-dev

// ✅ 改成从环境变量读 endpoint
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';

const client = new DynamoDBClient({
  ...(process.env.DYNAMODB_ENDPOINT && {
    endpoint: process.env.DYNAMODB_ENDPOINT,
    region: 'us-east-1',
    credentials: {
      accessKeyId: 'local',
      secretAccessKey: 'local',
    },
  }),
});

export const dynamo = DynamoDBDocumentClient.from(client);


// 重构你的 restApiHandler 需要解决的核心痛点是：让 parser 插件能够根据请求方法（GET vs POST）自动识别校验路径参数还是请求体，同时保持代码简洁并集成企业级的错误处理。
// 以下是优化后的版本，参考了你提供的 Powertools 标准实现并进行了精简化：
// 1. 核心重构代码
// import { parser } from '@aws-lambda-powertools/parser/middleware';
// import middy, { MiddlewareObj } from '@middy/core';
// import httpHeaderNormalizer from '@middy/http-header-normalizer';
// import { APIGatewayProxyEvent, APIGatewayProxyResult, Context } from 'aws-lambda';
// import { output, ZodError, ZodType } from 'zod';
// import { AppError } from '../utils/errors';

// /**
//  * 核心优化：自动识别校验源
//  * GET/DELETE 校验 pathParameters，POST/PUT/PATCH 校验 body
//  */
// const getValidationTarget = (event: APIGatewayProxyEvent) => {
//   const method = event.httpMethod?.toUpperCase();
//   if (['GET', 'DELETE'].includes(method)) {
//     // 合并路径参数和查询参数进行统一校验
//     return { ...event.pathParameters, ...event.queryStringParameters };
//   }
//   // 对于有 Body 的请求，如果是字符串则尝试解析（兼容手动模拟 event 的情况）
//   return typeof event.body === 'string' ? JSON.parse(event.body) : event.body;
// };

// export const restApiHandler = <R extends ZodType, T extends ZodType>(options: {
//   requestSchema: R;
//   responseSchema?: T;
// }) => {
//   const wrapper = middy();

//   // 1. 标准化 Header (解决大小写不一致问题)
//   wrapper.use(httpHeaderNormalizer());

//   // 2. 注入验证逻辑：利用 Powertools Parser
//   // 注意：我们在调用 handler 时手动进行数据预处理，以适配不同方法的校验源
//   wrapper.use({
//     before: (request) => {
//       const target = getValidationTarget(request.event);
//       // 将处理后的数据存回 event.body 供 parser 消费
//       request.event.body = target;
//     }
//   });

//   wrapper.use(parser({ schema: options.requestSchema }));

//   // 3. 错误处理 (必须在最后 use，因为 onError 是反向执行的)
//   wrapper.use(handleApiErrors());

//   // 4. 响应校验
//   if (options.responseSchema) {
//     wrapper.use(validateResponse(options.responseSchema));
//   }

//   return {
//     handler: (handler: (data: output<R>, context: Context) => Promise<any>) => {
//       return wrapper.handler(async (event: any, context: Context) => {
//         // 这里的 event.body 已经是经过 parser 校验并清洗过的干净数据
//         const result = await handler(event.body, context);

//         // 统一构造成功响应
//         return {
//           statusCode: 200,
//           headers: { 'Content-Type': 'application/json' },
//           body: JSON.stringify(result),
//         };
//       });
//     },
//   };
// };

// 2. 响应校验与错误处理优化
// export const validateResponse = (schema: ZodType): MiddlewareObj => ({
//   after: (request) => {
//     const { response } = request;
//     if (response?.body && response.statusCode === 200) {
//       try {
//         const data = typeof response.body === 'string' ? JSON.parse(response.body) : response.body;
//         schema.parse(data);
//       } catch (e) {
//         // 生产环境建议只打日志，不抛出异常给前端，防止 500
//         console.error('[Response Validation Error]', e);
//         throw e;
//       }
//     }
//   },
// });

// export const handleApiErrors = (): MiddlewareObj => ({
//   onError: (request) => {
//     const error = request.error as any;

//     // 逻辑：优先识别业务错误 -> Zod 校验错误 -> 其他系统错误
//     let statusCode = 500;
//     let responseBody: any = { message: 'Internal Server Error' };

//     if (error instanceof AppError) {
//       statusCode = error.statusCode;
//       responseBody = {
//         success: false,
//         message: error.message,
//         error: { code: error.errorCode, details: error.details },
//       };
//     } else if (error instanceof ZodError || error?.name === 'ZodError' || error?.cause instanceof ZodError) {
//       const zodErr = error instanceof ZodError ? error : (error.cause as ZodError);
//       statusCode = 400;
//       responseBody = {
//         message: 'Validation Failed',
//         errors: zodErr.issues.map((i) => ({
//           path: i.path.join('.'),
//           message: i.message,
//         })),
//       };
//     } else if (error?.name === 'ParseError' || error?.name === 'UnprocessableEntityError') {
//       statusCode = 400;
//       responseBody = { message: 'Invalid JSON format' };
//     }

//     request.response = {
//       statusCode,
//       headers: { 'Content-Type': 'application/json' },
//       body: JSON.stringify(responseBody),
//     };
//   },
// });

// 3. 这次重构解决了哪些问题？
// ✅ 解决了 GET 请求的 userId 校验问题
// 通过 getValidationTarget 函数，我们手动将 pathParameters 提取出来交给 parser。这样你的 getUser 请求只需像下面这样写，就能自动校验路径上的 userId：
// export const get = restApiHandler({
//   requestSchema: z.object({ userId: z.string().uuid() })
// }).handler(async (data) => {
//   return await userService.get(data.userId); // data 自动从 path 提取
// });

// ✅ 解决了 415 Unsupported Media Type
// 因为我们移除了严格的 httpJsonBodyParser，并在 getValidationTarget 中手动处理了 JSON.parse。即使你的测试中忘记传 Content-Type，代码也能正常运行。
// ✅ 保证了测试的兼容性
// 在 getValidationTarget 中有一行 typeof event.body === 'string' ? ...。这保证了无论你在 Jest 测试中传入的是对象还是字符串，中间件都能识别。
// ✅ 规范了响应格式
// 在 handler 返回处统一包裹了 statusCode: 200 和 JSON.stringify，你不需要在每个业务函数里重复写响应结构了。
// 💡 下一步建议
// 你可以尝试在 handleApiErrors 中加入 Logger（如 Powertools Logger），这样当生产环境发生 ZodError 时，你可以通过 cortexId 快速定位是前端哪个字段传错了。
// 你想让我帮你针对这个重构后的版本，重写一遍你之前的那个 getUser 测试用例吗？

// 4. 单元测试 (tests/user.spec.ts)
// 验证 CRUD 的核心逻辑。
// import { describe, it, expect } from 'vitest';
// import { create } from '../src/functions/user/handler';
// import { mockContext } from './test-utils';

// describe('User CRUD - Create', () => {
//   it('should successfully create a user with valid data', async () => {
//     const event = {
//       body: JSON.stringify({
//         username: 'gregli',
//         email: 'greg@example.com'
//       })
//     };

//     const result = await create(event as any, mockContext);
//     const body = JSON.parse(result.body);

//     expect(result.statusCode).toBe(200);
//     expect(body).toHaveProperty('id');
//     expect(body.username).toBe('gregli');
//   });

//   it('should return 400 when email is invalid', async () => {
//     const event = {
//       body: JSON.stringify({ username: 'greg', email: 'not-an-email' })
//     };

//     const result = await create(event as any, mockContext);
//     expect(result.statusCode).toBe(400);
//     expect(JSON.parse(result.body).message).toBe('Validation Failed');
//   });
// });

// 💡 核心设计点：
//  * DRY (Don't Repeat Yourself): UserSchema 是单一事实来源，校验、类型推断和文档生成全部共享这一份代码。
//  * 契约优先: 即使后端代码写错了（例如多返回了敏感字段 password），responseSchema 的 parse 也会拦截它，防止数据泄露。
//  * 错误一致性: 无论是 Zod 校验失败还是 NOT_FOUND，前端收到的 JSON 结构始终一致。
// 既然你提到了异步解耦，需要我帮你展示如何在一个 User 创建成功后，通过 SQS 异步发送欢迎邮件的实现吗？

// 为了让你彻底理解 Zod Schema (模具/警察) 和 z.infer (规格说明/名片) 的协作，我们来看一个真实的业务场景：用户修改密码。
// 这个场景包含了一个复杂的业务逻辑：确认密码必须与新密码一致。
// 1. 编写 Schema (Runtime - 运行时)
// 这是你的“单一事实来源”。它不仅定义了结构，还包含了逻辑校验。
// import { z } from 'zod';

// // 1. 定义 Schema
// export const UpdatePasswordSchema = z.object({
//   oldPassword: z.string().min(8),
//   newPassword: z.string().min(8),
//   confirmPassword: z.string().min(8),
// })
// .refine((data) => data.newPassword === data.confirmPassword, {
//   message: "Passwords don't match",
//   path: ["confirmPassword"], // 错误信息会挂在 confirmPassword 字段上
// });

// // 2. 从 Schema 推导出 TypeScript 类型 (Compile-time - 编译时)
// export type UpdatePasswordInput = z.infer<typeof UpdatePasswordSchema>;

// 2. 在业务代码中应用
// 看这两者是如何分工的：
// // 函数签名使用 z.infer 导出的类型：提供开发时的自动补全
// async function changeUserPassword(data: UpdatePasswordInput) {
//   // 这里 data.newPassword 是有代码提示的
//   console.log(`Updating password to: ${data.newPassword}`);
//   // 执行数据库操作...
// }

// // Lambda Handler 使用 Schema：处理不安全的外部数据
// export const handler = async (event: any) => {
//   try {
//     // 运行时拦截：如果 confirmPassword 不匹配，这里直接抛出 ZodError
//     const validatedData = UpdatePasswordSchema.parse(JSON.parse(event.body));

//     // 校验通过后，传入业务函数
//     await changeUserPassword(validatedData);

//     return { statusCode: 200, body: 'Success' };
//   } catch (e) {
//     // 错误处理...
//   }
// };

// 3. 核心差异的直观体现
// | 场景 | 使用 Schema (UpdatePasswordSchema) | 使用 Type (UpdatePasswordInput) |
// |---|---|---|
// | 如果你删掉其中一个字段 | parse() 会报错，并返回 400 Bad Request。 | TypeScript 编译器会标红，提示缺少属性。 |
// | 如果两个密码不一致 | .refine() 会拦截并报错（运行时）。 | 无法识别。TS 只知道它们都是 string，不知道它们的值是否相等。 |
// | 在编译成 JS 后 | 代码依然存在，继续保护你的服务器。 | 完全消失。JS 引擎不知道什么是 UpdatePasswordInput。 |
// 4. 为什么 Zod 叫 "Schema-First"？
// 在传统的开发中，你可能先写 interface User { ... }。但 interface 无法在运行时阻止前端传错数据。
// Zod 的逻辑是：
//  * 你先定义 Schema (具备校验能力)。
//  * 通过 z.infer 免费获得 Type。
//  * 通过 zod-to-openapi 免费获得 Swagger/OpenAPI 文档。
// 💡 总结
//  * Schema 是你的防线：在 API 入口、数据库出口使用。
//  * Type 是你的向导：在函数传参、组件定义、逻辑编写时使用。
// 既然掌握了 .refine()，你想看看如何结合 z.transform()，在 Schema 校验的同时自动把日期字符串（"2026-01-01"）转换成真正的 JS Date 对象吗？

// 既然我们要引入 Amazon SQS 来处理“用户注册后发送欢迎邮件”的异步解耦逻辑，这不仅能缩短 API 的响应时间（因为发邮件通常比较慢），还能提高系统的稳定性。
// 以下是工业级的实现方案，包含了 Lambda 生产者、SQS 配置以及消费者逻辑。
// 1. 架构逻辑：生产者 (Producer) 与 消费者 (Consumer)
//  * API Lambda (Producer): 处理用户创建逻辑，将 welcome-email 任务丢入 SQS，然后立即给前端返回 201 Created。
//  * Worker Lambda (Consumer): 由 SQS 触发，从队列中取出消息并调用邮件服务（如 AWS SES）。
// 2. 发送消息到 SQS (Producer 逻辑)
// 修改你的 user.handler.ts，在成功创建用户后增加推送到 SQS 的逻辑：
// import { SQSClient, SendMessageCommand } from "@aws-sdk/client-sqs";

// const sqsClient = new SQSClient({});

// export const create = restApiHandler({
//   requestSchema: CreateUserRequest,
//   responseSchema: UserSchema,
// }).handler(async (body) => {
//   // 1. 业务逻辑：保存到数据库 (假设已完成)
//   const newUser = { ...body, id: 'uuid-123', createdAt: new Date().toISOString() };

//   // 2. 异步解耦：推送到 SQS
//   try {
//     await sqsClient.send(new SendMessageCommand({
//       QueueUrl: process.env.WELCOME_EMAIL_QUEUE_URL,
//       MessageBody: JSON.stringify({
//         email: newUser.email,
//         username: newUser.username,
//         type: 'WELCOME_EMAIL'
//       }),
//     }));
//   } catch (error) {
//     console.error("Failed to push to SQS:", error);
//     // 注意：通常不因为发邮件失败而让用户注册失败，这里仅记录日志
//   }

//   return newUser;
// });

// 3. 处理 SQS 消息 (Consumer 逻辑)
// 创建一个新的 Lambda 处理函数 src/functions/workers/email-worker.ts。由于这不是 API 接口，我们不需要 restApiHandler，直接使用原生的 SQS 事件处理。
// import { SQSEvent, SQSHandler } from 'aws-lambda';

// export const handler: SQSHandler = async (event: SQSEvent) => {
//   for (const record of event.Records) {
//     const payload = JSON.parse(record.body);

//     console.log(`Processing ${payload.type} for ${payload.email}...`);

//     // 模拟发送邮件逻辑
//     await sendEmail(payload.email, `Welcome, ${payload.username}!`);

//     // 如果执行成功，Lambda 返回后 SQS 会自动删除该消息
//     // 如果抛出异常，SQS 会根据 Retry Policy 进行重试
//   }
// };

// async function sendEmail(to: string, content: string) {
//   // 调用 AWS SES 或第三方服务 (SendGrid/Mailchimp)
//   return new Promise((resolve) => setTimeout(resolve, 500));
// }

// 4. Serverless 资源配置 (YAML)
// 在 serverless.yml 中定义队列和触发器：
// functions:
//   createUser:
//     handler: src/functions/user/handler.create
//     events:
//       - http:
//           path: users
//           method: post
//     environment:
//       WELCOME_EMAIL_QUEUE_URL: !Ref WelcomeEmailQueue

//   emailWorker:
//     handler: src/functions/workers/email-worker.handler
//     events:
//       - sqs:
//           arn: !GetAtt WelcomeEmailQueue.Arn
//           batchSize: 10 # 每次处理最多 10 条消息，提升效率

// resources:
//   Resources:
//     WelcomeEmailQueue:
//       Type: AWS::SQS::Queue
//       Properties:
//         QueueName: welcome-email-queue-${sls:stage}
//         VisibilityTimeout: 30 # 应大于 Lambda 的超时时间

// 5. 为什么这是“工业级”做法？
//  * 容错性 (Resiliency)：如果邮件服务暂时宕机，消息会留在 SQS 中自动重试，而不会导致用户看到注册失败。
//  * 削峰填谷 (Load Leveling)：如果有 1 万人同时注册，API 会迅速处理，而 emailWorker 会根据配置的并发限制平稳地消化这些邮件任务，不会压垮邮件服务器。
//  * 可观测性：你可以通过 CloudWatch 监控 ApproximateNumberOfMessagesVisible，如果队列堆积，说明邮件服务性能遇到瓶颈。
// 💡 下一步建议
// 既然引入了 SQS，你可能需要处理 Dead Letter Queue (DLQ)，即“死信队列”。当一条消息重试多次（比如 3 次）仍然失败时，将其移入 DLQ，防止无限循环消耗资源。
// 需要我帮你把 DLQ 的配置和处理逻辑也补充到 serverless.yml 中吗？

// .env 是存环境变量的纯文本文件，格式是 KEY=VALUE：

// # .env
// DYNAMODB_ENDPOINT=http://localhost:8000
// USERS_TABLE=my-service-users-dev
// AWS_REGION=us-east-1

// 为什么用

// 代码里不能 hardcode 配置  ← 不同环境值不同，且敏感信息不能提交 git
//                                 ↓
// 把配置抽到 .env 文件      ← 本地/dev/prod 各自一份，代码不变

// 怎么用
// Node.js 里读取：

// // 需要先加载 .env，才能用 process.env
// import 'dotenv/config';  // 或 require('dotenv').config()

// console.log(process.env.USERS_TABLE);  // 'my-service-users-dev'

// Serverless Framework 自动加载：

// // serverless.ts — 自动把 .env 注入到 Lambda 环境变量
// const serverlessConfiguration: AWS = {
//   useDotenv: true,   // ← 加这一行
//   provider: {
//     environment: {
//       USERS_TABLE: '${env:USERS_TABLE}',           // 从 .env 读
//       DYNAMODB_ENDPOINT: '${env:DYNAMODB_ENDPOINT}',
//     },
//   },
// };

// 文件规范

// .env              ← 本地实际值，加入 .gitignore，不提交
// .env.example      ← 模板，只写 key 不写值，提交 git 给团队参考
// .env.prod         ← 生产值，绝对不提交 git

// # .gitignore
// .env
// .env.prod
// .env.local

// # 只提交这个
// .env.example

// # .env.example（提交 git，告诉团队需要哪些变量）
// DYNAMODB_ENDPOINT=
// USERS_TABLE=
// AWS_REGION=

// 新人上手流程

// git clone ...
// cp .env.example .env   # 复制模板
// vim .env               # 填入本地的值
// pnpm dev               # 跑起来

// 查看本地dynamodb
// AWS_ACCESS_KEY_ID=local AWS_SECRET_ACCESS_KEY=local aws dynamodb list-tables \
//   --endpoint-url http://localhost:8000 \
//   --region us-east-1
