import type { APIGatewayProxyEvent } from '@aws-lambda-powertools/parser/types';

export const apiGatewayMockEvent: APIGatewayProxyEvent = {
  resource: '/{proxy+}',
  path: '/test/path',
  httpMethod: 'POST',
  headers: {
    Accept: 'application/json',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'en-US,en;q=0.9',
    'Cache-Control': 'no-cache',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-Country': 'US',
    'Content-Type': 'application/json',
    Host: '1234567890.execute-api.us-east-1.amazonaws.com',
    'User-Agent': 'Custom User Agent String',
    Via: '1.1 abcdef1234567890.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'abcdefg1234567890==',
    'X-Amzn-Trace-Id': 'Root=1-67891233-abcdef1234567890abcdef1234567890',
    'X-Forwarded-For': '192.0.2.1, 203.0.113.1',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
  },
  multiValueHeaders: {
    Accept: ['application/json'],
    'X-Forwarded-For': ['192.0.2.1', '203.0.113.1'],
  },
  queryStringParameters: {
    param1: 'value1',
    param2: 'value2',
  },
  multiValueQueryStringParameters: {
    param1: ['value1', 'value1b'],
    param2: ['value2'],
  },
  pathParameters: {
    proxy: 'test/path',
  },
  stageVariables: {
    stageVarName: 'stageVarValue',
  },
  requestContext: {
    accountId: '123456789012',
    resourceId: 'abcd123',
    stage: 'dev',
    requestId: 'c1234567-d89e-1234-a567-1234567890ab',
    protocol: 'HTTP/1.1',
    requestTime: '19/Aug/2025:13:45:30 +0000',
    requestTimeEpoch: 1755611130000,
    path: '/dev/test/path',
    identity: {
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '192.0.2.1',
      principalOrgId: null,
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent: 'Custom User Agent String',
      user: null,
    },
    resourcePath: '/{proxy+}',
    httpMethod: 'POST',
    apiId: 'abcdef1234',
  },
  body: '{ "test": "value" }',
  isBase64Encoded: false,
};
