//@awshost = https://lk4713f0ta.execute-api.us-east-1.amazonaws.com
@awshost = https://d4yr1pdcs1.execute-api.us-east-1.amazonaws.com

# Create User
POST {{awshost}}/dev/user
content-type: application/json

{
    "name": "test user name",
    "email": "test@test.com"
}

###
# Create user - Invalid email
POST {{awshost}}/dev/user
content-type: application/json

{
    "name": "test user name",
    "email": "test"
}

###
# Create user - Invalid name & email
POST {{awshost}}/dev/user
content-type: application/json

{
    "name": "1",
    "email": "2"
}

###
# Create user - Invalid json
POST {{awshost}}/dev/user
content-type: application/json

{
    123
}

###
# Get user by userId
GET {{awshost}}/dev/user/f1fc2237-6614-4312-9ba9-a465f8c9fc0c
content-type: application/json
